import type { Profile } from "../types";

// Synthetic demo-cast profiles — fictional builders designed to give the
// matcher enough signal variety (skills × domains × commitment × values) for
// the compatibility agent to rank meaningfully. Wallets are randomly
// generated; these are NPC accounts, not people. The `github` field is
// intentionally null because we don't want the frontend or GitHub API to
// chase 404s for handles that don't exist.
export const SEED_PROFILES: Profile[] = [
  {
    id: "0x3fab2c7d1a90b5e88a51a62c9c4ea1b30f0d5301",
    wallet: "0x3fab2c7d1a90b5e88a51a62c9c4ea1b30f0d5301",
    displayName: "fenway.eth",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=fenway",
    bio: "L1 protocol researcher — spent the last 18 months on data-availability sampling proofs. Wrote two EIP drafts, mostly living in Rust + Yul. Looking for a builder who can turn my research into a shippable client and isn't afraid of merkle trees.",
    skills: ["Solidity", "Yul", "Rust", "ZK", "consensus-design"],
    domains: ["L1 infra", "DA layers", "rollups"],
    values: ["open-source", "decentralisation", "long-term"],
    commitment: "full-time",
    onchainReceipts: [
      { kind: "deployed_contract", chainId: 1, note: "DA proof verifier MVP" },
      { kind: "dao_vote", chainId: 1, note: "Voted NO on Arbitrum Short-Term Incentive Program" },
    ],
    githubStats: undefined,
    reputation: { trustScore: 88, redFlags: [], endorsements: 6 },
    createdAt: 1_745_000_000,
    seeded: true,
  },
  {
    id: "0x9c1e52a7b03f19e84c0f1a3d2b88b4d6f0e1c4a2",
    wallet: "0x9c1e52a7b03f19e84c0f1a3d2b88b4d6f0e1c4a2",
    displayName: "lumen.eth",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=lumen",
    bio: "Built 3 live yield protocols across Arbitrum + Base, current TVL $14M combined. Obsessed with gas-efficient AMMs and correct-by-construction accounting. Not interested in another UI-first memecoin project.",
    skills: ["Solidity", "AMM-design", "fixed-point math", "Foundry", "gas-optimisation"],
    domains: ["DeFi", "yield", "AMMs", "lending"],
    values: ["revenue-first", "rigour", "decentralisation"],
    commitment: "full-time",
    onchainReceipts: [
      { kind: "deployed_contract", chainId: 42161, note: "YieldLab v2 vault" },
      { kind: "deployed_contract", chainId: 8453, note: "Concentrated-liquidity AMM" },
    ],
    githubStats: undefined,
    reputation: { trustScore: 82, redFlags: [], endorsements: 4 },
    createdAt: 1_744_300_000,
    seeded: true,
  },
  {
    id: "0x5d7a3f9b21e0c4a876b9e1f2d3c4a5b6e7f80912",
    wallet: "0x5d7a3f9b21e0c4a876b9e1f2d3c4a5b6e7f80912",
    displayName: "quiver",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=quiver",
    bio: "Frontend + design for Web3 products. Shipped the UIs for two cycle-1 DeFi dApps judged as 'actually usable'. I speak wagmi, viem, RainbowKit, and Figma. Pair me with someone who writes great contracts but can't make them feel good.",
    skills: ["React", "Next.js", "wagmi/viem", "design-systems", "Tailwind", "Figma"],
    domains: ["Frontend", "wallet UX", "DeFi UI"],
    values: ["craft", "user-first", "open-source"],
    commitment: "full-time",
    onchainReceipts: [
      { kind: "notable_tx", chainId: 8453, note: "deployed own ENS subdomain registry" },
    ],
    githubStats: undefined,
    reputation: { trustScore: 90, redFlags: [], endorsements: 9 },
    createdAt: 1_744_900_000,
    seeded: true,
  },
  {
    id: "0x8f21d34b6a5c7e90e2b4f6c1d8a9b0c2d4e5f601",
    wallet: "0x8f21d34b6a5c7e90e2b4f6c1d8a9b0c2d4e5f601",
    displayName: "blaze",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=blaze",
    bio: "Ran 6 meme launches on Four.meme + pump.fun, two hit $2M mcap. Understand the exact moment a chart flips from pump to dump. Looking for a technical cofounder to build an honest launchpad — tired of the rug economy.",
    skills: ["growth", "trading-psych", "meme-ops", "community-building"],
    domains: ["memecoins", "launchpads", "BNB/Base"],
    values: ["revenue-first", "honesty", "community-first"],
    commitment: "full-time",
    onchainReceipts: [
      { kind: "token_mint", chainId: 56, note: "launched $PEPI (peaked $2.1M mcap, down 60%)" },
    ],
    githubStats: undefined,
    reputation: { trustScore: 60, redFlags: ["primarily trader background, light on shipped infra"], endorsements: 2 },
    createdAt: 1_745_400_000,
    seeded: true,
  },
  {
    id: "0x2a1b9c7d5e0f4a6b3c8d2e5f1a4b7c9e0d2f3a4b",
    wallet: "0x2a1b9c7d5e0f4a6b3c8d2e5f1a4b7c9e0d2f3a4b",
    displayName: "sage.dao",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=sage",
    bio: "Treasury + governance operator for two $50M+ DAOs. Snapshot proposal count: 47. I can turn messy community fights into shipped motions. Not a dev — looking for a technical partner to build the governance tooling I keep hand-rolling in Python.",
    skills: ["governance", "treasury-management", "Snapshot", "proposal-writing"],
    domains: ["DAOs", "governance", "treasury"],
    values: ["decentralisation", "community-first", "long-term"],
    commitment: "side-project",
    onchainReceipts: [
      { kind: "dao_vote", chainId: 1, note: "authored Nouns Prop 412 (extend auction by 24h)" },
      { kind: "dao_vote", chainId: 1, note: "47 votes cast across 8 DAOs since 2023" },
    ],
    githubStats: undefined,
    reputation: { trustScore: 85, redFlags: [], endorsements: 11 },
    createdAt: 1_742_500_000,
    seeded: true,
  },
  {
    id: "0x6e3a5b7c9d1f2a4b6c8d0e2f4a6b8c0d2e4f6a8b",
    wallet: "0x6e3a5b7c9d1f2a4b6c8d0e2f4a6b8c0d2e4f6a8b",
    displayName: "aranea",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=aranea",
    bio: "ZK cryptographer. PhD halfway through. Live in Circom + Noir. Built a private voting circuit used in one small DAO. Want to apply ZK to something dumb and fun, not another 'privacy-preserving institutional settlement' deck.",
    skills: ["ZK", "Circom", "Noir", "cryptography", "rust"],
    domains: ["privacy", "ZK apps", "cryptography"],
    values: ["rigour", "open-source", "curiosity"],
    commitment: "hobby",
    onchainReceipts: [
      { kind: "deployed_contract", chainId: 1, note: "anonymous voting circuit verifier" },
    ],
    githubStats: undefined,
    reputation: { trustScore: 80, redFlags: [], endorsements: 5 },
    createdAt: 1_743_800_000,
    seeded: true,
  },
  {
    id: "0xabf4c7d2e9f0a1b3c5d7e9f0a2b4c6d8e0f2a4b6",
    wallet: "0xabf4c7d2e9f0a1b3c5d7e9f0a2b4c6d8e0f2a4b6",
    displayName: "kato",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=kato",
    bio: "Shipped 4 solo hackathon projects, 2 won. Generalist — contracts, backend, frontend, can even draw. Looking for a specialist to go deep with on one idea instead of my usual 'ship, move on' cycle.",
    skills: ["full-stack", "Solidity", "Next.js", "Bun", "design-enough"],
    domains: ["indie apps", "hackathons", "social"],
    values: ["ship-fast", "craft", "community-first"],
    commitment: "side-project",
    onchainReceipts: [
      { kind: "deployed_contract", chainId: 8453, note: "ETHGlobal finalist project (community tipping)" },
      { kind: "deployed_contract", chainId: 10, note: "mini POAP-clone for meetups" },
    ],
    githubStats: undefined,
    reputation: { trustScore: 78, redFlags: ["high repo count, inconsistent long-term maintenance"], endorsements: 7 },
    createdAt: 1_745_200_000,
    seeded: true,
  },
  {
    id: "0x14e8a3b6c9d2f0a1b4c6d8e0f2a4b6c8d0e2f4a6",
    wallet: "0x14e8a3b6c9d2f0a1b4c6d8e0f2a4b6c8d0e2f4a6",
    displayName: "rho",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=rho",
    bio: "Community lead across 4 Discords, collectively 120k members. I can make a new project feel alive on day 1. No dev skills — don't try to get me to write Solidity. Pair me with a dev who can't be bothered with Discord politics.",
    skills: ["community-ops", "Discord", "Twitter-marketing", "moderation", "support"],
    domains: ["community", "growth", "ops"],
    values: ["community-first", "honesty"],
    commitment: "full-time",
    onchainReceipts: [],
    githubStats: undefined,
    reputation: { trustScore: 75, redFlags: ["zero on-chain activity"], endorsements: 14 },
    createdAt: 1_744_100_000,
    seeded: true,
  },
  {
    id: "0x7b2d4e6f8a0c1d3e5f7a9b0c2d4e6f8a0b2c4d6e",
    wallet: "0x7b2d4e6f8a0c1d3e5f7a9b0c2d4e6f8a0b2c4d6e",
    displayName: "orion",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=orion",
    bio: "Smart contract auditor, Code4rena top-30 in 2024. Found 2 criticals, 11 highs across audit contests. Happy to be the 'adult in the room' for a team that moves fast but doesn't want to lose funds.",
    skills: ["Solidity-audit", "Foundry", "static-analysis", "invariant-testing"],
    domains: ["security", "audits", "DeFi"],
    values: ["rigour", "open-source"],
    commitment: "side-project",
    onchainReceipts: [
      { kind: "notable_tx", chainId: 1, note: "submitted 14 audit reports on Code4rena" },
    ],
    githubStats: undefined,
    reputation: { trustScore: 92, redFlags: [], endorsements: 8 },
    createdAt: 1_743_000_000,
    seeded: true,
  },
  {
    id: "0x23f6a8b0c2d4e6f8a0b2c4d6e8f0a2b4c6d8e0f2",
    wallet: "0x23f6a8b0c2d4e6f8a0b2c4d6e8f0a2b4c6d8e0f2",
    displayName: "mira",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=mira",
    bio: "Web3 product designer. NFT art background, now obsessed with making wallets feel like apps, not like 1997 Linux menus. Portfolio includes two shipped wallet UX redesigns and a Farcaster client.",
    skills: ["product-design", "UI/UX", "Figma", "Framer", "illustration"],
    domains: ["design", "wallet UX", "social"],
    values: ["craft", "user-first"],
    commitment: "full-time",
    onchainReceipts: [
      { kind: "token_mint", chainId: 8453, note: "NFT collection 'Lattice' — 500 unique" },
    ],
    githubStats: undefined,
    reputation: { trustScore: 83, redFlags: [], endorsements: 5 },
    createdAt: 1_744_700_000,
    seeded: true,
  },
  {
    id: "0x91c3b5d7e9f0a2b4c6d8e0f2a4b6c8d0e2f4a6b8",
    wallet: "0x91c3b5d7e9f0a2b4c6d8e0f2a4b6c8d0e2f4a6b8",
    displayName: "helios",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=helios",
    bio: "On-chain game dev. 8 years of Unity, now building fully-onchain roguelikes on Base. Obsessed with game-feel + actually-fun-to-play, not 'points you get for wallet activity'.",
    skills: ["Unity", "Solidity", "game-design", "randomness", "sessions"],
    domains: ["gaming", "on-chain games", "Base"],
    values: ["craft", "user-first", "ship-fast"],
    commitment: "full-time",
    onchainReceipts: [
      { kind: "deployed_contract", chainId: 8453, note: "Roguelike session contract (2,300 plays)" },
    ],
    githubStats: undefined,
    reputation: { trustScore: 79, redFlags: [], endorsements: 4 },
    createdAt: 1_744_500_000,
    seeded: true,
  },
  {
    id: "0x5a7b9c0d2e4f6a8b0c2d4e6f8a0b2c4d6e8f0a2b",
    wallet: "0x5a7b9c0d2e4f6a8b0c2d4e6f8a0b2c4d6e8f0a2b",
    displayName: "nyx",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=nyx",
    bio: "Infra eng — run custom indexers, RPC load balancers, and a private archive node fleet. If your dApp needs to serve data faster than Alchemy at 1/5 the cost, talk to me.",
    skills: ["Go", "Postgres", "indexers", "RPC", "DevOps", "Rust"],
    domains: ["infra", "indexing", "data"],
    values: ["rigour", "revenue-first"],
    commitment: "full-time",
    onchainReceipts: [
      { kind: "notable_tx", chainId: 1, note: "Ran a public mempool indexer (24k rps peak)" },
    ],
    githubStats: undefined,
    reputation: { trustScore: 86, redFlags: [], endorsements: 6 },
    createdAt: 1_743_400_000,
    seeded: true,
  },
  {
    id: "0xcf2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8a",
    wallet: "0xcf2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8a",
    displayName: "vega",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=vega",
    bio: "Growth hacker. Scaled 2 crypto apps from 0 to 50k users. Paid acquisition + viral-loop design + founder-mode Twitter. Looking for a product I can honestly champion; ghostwriting another farming guide burnt me out.",
    skills: ["paid-acquisition", "Twitter-growth", "SEO", "funnels", "viral-loops"],
    domains: ["growth", "marketing", "consumer"],
    values: ["revenue-first", "community-first", "honesty"],
    commitment: "side-project",
    onchainReceipts: [],
    githubStats: undefined,
    reputation: { trustScore: 72, redFlags: ["zero deployed contracts"], endorsements: 4 },
    createdAt: 1_744_000_000,
    seeded: true,
  },
  {
    id: "0x38b5c7d9e0f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0",
    wallet: "0x38b5c7d9e0f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0",
    displayName: "parsa",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=parsa",
    bio: "Lawyer turned crypto-native BD. Structured 4 token launches through EU MiCA. I am extremely not a dev; I am the person who keeps your launch from becoming an SEC press release. If your stack is 'ready to ship' and you haven't talked to a lawyer, we should talk.",
    skills: ["legal", "compliance", "token-structuring", "BD", "MiCA"],
    domains: ["legal", "compliance", "ops"],
    values: ["rigour", "long-term"],
    commitment: "side-project",
    onchainReceipts: [],
    githubStats: undefined,
    reputation: { trustScore: 77, redFlags: ["zero on-chain activity, zero GitHub"], endorsements: 3 },
    createdAt: 1_742_000_000,
    seeded: true,
  },
  {
    id: "0x76d8e0f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4",
    wallet: "0x76d8e0f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4",
    displayName: "tessera",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=tessera",
    bio: "On-chain data scientist. Wrote the Dune dashboard three protocols now reference. Can spot a wash-trading cluster in five minutes. Looking to build something that puts the tools I keep hand-rolling into a product.",
    skills: ["SQL", "Python", "Dune", "data-science", "analytics"],
    domains: ["data", "analytics", "on-chain"],
    values: ["rigour", "open-source", "curiosity"],
    commitment: "side-project",
    onchainReceipts: [
      { kind: "notable_tx", chainId: 1, note: "Dune dashboard referenced by 3 protocols' docs" },
    ],
    githubStats: undefined,
    reputation: { trustScore: 81, redFlags: [], endorsements: 5 },
    createdAt: 1_743_500_000,
    seeded: true,
  },
];
